# Generated by Django 5.2.1 on 2025-06-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Index",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carousel_header", models.CharField(max_length=150)),
                ("carousel_line", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        height_field=100,
                        max_length=200,
                        upload_to="carousal-image",
                        width_field=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
