# Generated by Django 5.2.1 on 2025-06-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OurApproach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approach_header", models.CharField(max_length=150)),
                ("approach_line", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="index",
            name="carousel_line",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="index",
            name="image",
            field=models.ImageField(upload_to="carousal-image"),
        ),
    ]
