# Generated by Django 5.2.1 on 2025-06-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0002_ourapproach_alter_index_carousel_line_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ourapproach",
            name="approach_line",
            field=models.CharField(max_length=500),
        ),
    ]
