# Generated by Django 5.2.1 on 2025-06-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0003_alter_ourapproach_approach_line"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChooseUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chooseus_header", models.CharField(max_length=150)),
                ("chooseus_line", models.CharField(max_length=300)),
                ("image", models.ImageField(upload_to="carousal-image")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
