# Generated by Django 5.2.1 on 2025-06-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0006_clients"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourcingSolutions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
