# Generated by Django 5.2.1 on 2025-06-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0009_visitor"),
    ]

    operations = [
        migrations.CreateModel(
            name="OurStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Our Story", max_length=50)),
                (
                    "description",
                    models.TextField(max_length=1000, verbose_name="Açıklama"),
                ),
                ("image", models.ImageField(upload_to="OurStory")),
            ],
        ),
        migrations.AlterField(
            model_name="chooseus",
            name="chooseus_header",
            field=models.CharField(max_length=150, verbose_name="Neden Biz"),
        ),
        migrations.AlterField(
            model_name="chooseus",
            name="chooseus_line",
            field=models.CharField(max_length=300, verbose_name="Neden Biz Açıklama"),
        ),
        migrations.AlterField(
            model_name="clients",
            name="image",
            field=models.ImageField(
                upload_to="client-image", verbose_name="Müşteri Logo"
            ),
        ),
        migrations.AlterField(
            model_name="clients",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Müşteri Adı"),
        ),
        migrations.AlterField(
            model_name="consultancyservices",
            name="description",
            field=models.TextField(max_length=500, verbose_name="Açıklama"),
        ),
        migrations.AlterField(
            model_name="consultancyservices",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Danışmanlık Hizmeti"),
        ),
        migrations.AlterField(
            model_name="index",
            name="carousel_header",
            field=models.CharField(max_length=150, verbose_name="Carousel Tanım"),
        ),
        migrations.AlterField(
            model_name="index",
            name="carousel_line",
            field=models.CharField(max_length=300, verbose_name="Carousel Açıklama"),
        ),
        migrations.AlterField(
            model_name="ourapproach",
            name="approach_header",
            field=models.CharField(max_length=150, verbose_name="Yaklaşımımız"),
        ),
        migrations.AlterField(
            model_name="ourapproach",
            name="approach_line",
            field=models.CharField(
                max_length=500, verbose_name="Yaklaşımımız Açıklama"
            ),
        ),
        migrations.AlterField(
            model_name="sourcingsolutions",
            name="description",
            field=models.TextField(max_length=500, verbose_name="Açıklama"),
        ),
        migrations.AlterField(
            model_name="sourcingsolutions",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Kaynak Çözümler"),
        ),
    ]
