# Generated by Django 5.2.1 on 2025-06-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0010_ourstory_alter_chooseus_chooseus_header_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ourapproach",
            name="approach_line",
            field=models.TextField(
                max_length=1000, verbose_name="Yaklaşımımız Açıklama"
            ),
        ),
    ]
