# Generated by Django 5.2.1 on 2025-06-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0011_alter_ourapproach_approach_line"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="consultancyservices",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="Açıklama"),
        ),
    ]
