# Generated by Django 5.2.1 on 2025-06-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0012_service_alter_consultancyservices_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcingsolutions",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="sourcing-solution"
            ),
        ),
    ]
