# Generated by Django 5.2.3 on 2025-08-13 13:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0015_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=350, verbose_name='Location')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('google_map', models.CharField(max_length=850, verbose_name='Google Map')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='ChooseUsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chooseus_header', models.CharField(max_length=150, verbose_name='Why Us')),
                ('chooseus_line', models.CharField(max_length=300, verbose_name='Why Us Description')),
            ],
            options={
                'verbose_name': 'Why Us Content',
                'verbose_name_plural': 'Why Us Contents',
            },
        ),
        migrations.CreateModel(
            name='ConsultancyServicesContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Consultancy Services')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Consultancy Service Content',
                'verbose_name_plural': 'Consultancy Service Contents',
            },
        ),
        migrations.CreateModel(
            name='IndexContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carousel_header', models.CharField(max_length=150, verbose_name='Carrousel Header')),
                ('carousel_line', models.CharField(max_length=300, verbose_name='Carrousel Description')),
            ],
            options={
                'verbose_name': 'Carrousel Content',
                'verbose_name_plural': 'Carrousel Contents',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Language Code')),
                ('name', models.CharField(max_length=50, verbose_name='Language Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='OurApproachContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approach_header', models.CharField(max_length=150, verbose_name='Our Approach')),
                ('approach_line', models.TextField(max_length=1000, verbose_name='Our Approach Description')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Our Approach Content',
                'verbose_name_plural': 'Our Approach Contents',
            },
        ),
        migrations.CreateModel(
            name='OurStoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Our Story Content',
                'verbose_name_plural': 'Our Story Contents',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Product Category Content',
                'verbose_name_plural': 'Product Category Contents',
            },
        ),
        migrations.CreateModel(
            name='ProductsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Products')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Product Content',
                'verbose_name_plural': 'Product Contents',
            },
        ),
        migrations.CreateModel(
            name='ServiceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_description', models.TextField(verbose_name='Services')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Service Content',
                'verbose_name_plural': 'Service Contents',
            },
        ),
        migrations.CreateModel(
            name='SourcingSolutionsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Sourcing Solutions')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Sourcing Solution Content',
                'verbose_name_plural': 'Sourcing Solution Contents',
            },
        ),
        migrations.DeleteModel(
            name='Adress',
        ),
        migrations.AlterModelOptions(
            name='chooseus',
            options={'ordering': ['order'], 'verbose_name': 'Why Us', 'verbose_name_plural': 'Why Us'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='consultancyservices',
            options={'ordering': ['order'], 'verbose_name': 'Consultancy Service', 'verbose_name_plural': 'Consultancy Services'},
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'ordering': ['order'], 'verbose_name': 'Carrousel', 'verbose_name_plural': 'Carrousels'},
        ),
        migrations.AlterModelOptions(
            name='ourapproach',
            options={'verbose_name': 'Our Approach', 'verbose_name_plural': 'Our Approaches'},
        ),
        migrations.AlterModelOptions(
            name='ourstory',
            options={'verbose_name': 'Our Story', 'verbose_name_plural': 'Our Story'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['order'], 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['order'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='sourcingsolutions',
            options={'ordering': ['order'], 'verbose_name': 'Sourcing Solution', 'verbose_name_plural': 'Sourcing Solutions'},
        ),
        migrations.RemoveField(
            model_name='chooseus',
            name='chooseus_header',
        ),
        migrations.RemoveField(
            model_name='chooseus',
            name='chooseus_line',
        ),
        migrations.RemoveField(
            model_name='consultancyservices',
            name='description',
        ),
        migrations.RemoveField(
            model_name='consultancyservices',
            name='name',
        ),
        migrations.RemoveField(
            model_name='index',
            name='carousel_header',
        ),
        migrations.RemoveField(
            model_name='index',
            name='carousel_line',
        ),
        migrations.RemoveField(
            model_name='ourapproach',
            name='approach_header',
        ),
        migrations.RemoveField(
            model_name='ourapproach',
            name='approach_line',
        ),
        migrations.RemoveField(
            model_name='ourstory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ourstory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_description',
        ),
        migrations.RemoveField(
            model_name='sourcingsolutions',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sourcingsolutions',
            name='name',
        ),
        migrations.AddField(
            model_name='chooseus',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='chooseus',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='consultancyservices',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='consultancyservices',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='index',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='index',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='ourapproach',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='ourstory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourstory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='ourstory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='products',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='sourcingsolutions',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='sourcingsolutions',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='chooseus',
            name='image',
            field=models.ImageField(upload_to='chooseus-image', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='image',
            field=models.ImageField(upload_to='client-image', verbose_name='Client Logo'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='index',
            name='image',
            field=models.ImageField(upload_to='carousal-image', verbose_name='Carrousel Images'),
        ),
        migrations.AlterField(
            model_name='ourstory',
            name='image',
            field=models.ImageField(upload_to='OurStory', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main_page.productcategory'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='path',
            field=models.CharField(max_length=255, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='referrer',
            field=models.URLField(blank=True, null=True, verbose_name='Referrer'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AddField(
            model_name='chooseuscontent',
            name='choose_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chooseus_content', to='main_page.chooseus'),
        ),
        migrations.AddField(
            model_name='consultancyservicescontent',
            name='consultancy_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultancyservices_content', to='main_page.consultancyservices'),
        ),
        migrations.AddField(
            model_name='indexcontent',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_content', to='main_page.index'),
        ),
        migrations.AddField(
            model_name='indexcontent',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.language', verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='consultancyservicescontent',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.language', verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='chooseuscontent',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.language', verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='ourapproachcontent',
            name='our_approach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ourapproach_content', to='main_page.ourapproach'),
        ),
        migrations.AddField(
            model_name='ourstorycontent',
            name='our_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ourstory_content', to='main_page.ourstory'),
        ),
        migrations.AddField(
            model_name='productcategorycontent',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcategory_content', to='main_page.productcategory'),
        ),
        migrations.AddField(
            model_name='productscontent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_content', to='main_page.products'),
        ),
        migrations.AddField(
            model_name='servicecontent',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_content', to='main_page.service'),
        ),
        migrations.AddField(
            model_name='sourcingsolutionscontent',
            name='sourcing_solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcingsolutions_content', to='main_page.sourcingsolutions'),
        ),
        migrations.AlterUniqueTogether(
            name='indexcontent',
            unique_together={('index', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='consultancyservicescontent',
            unique_together={('consultancy_service', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='chooseuscontent',
            unique_together={('choose_us', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='ourapproachcontent',
            unique_together={('our_approach', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='ourstorycontent',
            unique_together={('our_story', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='productcategorycontent',
            unique_together={('product_category', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='productscontent',
            unique_together={('product', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='servicecontent',
            unique_together={('service', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='sourcingsolutionscontent',
            unique_together={('sourcing_solution', 'language')},
        ),
    ]
