# Generated by Django 5.2.3 on 2025-08-13 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_address_chooseuscontent_consultancyservicescontent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
        migrations.RemoveField(
            model_name='address',
            name='location',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
        migrations.AddField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.CreateModel(
            name='AddressContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=350, verbose_name='Location')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_content', to='main_page.address')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Address Content',
                'verbose_name_plural': 'Address Contents',
                'unique_together': {('address', 'language')},
            },
        ),
    ]
