# Generated by Django 5.2.3 on 2025-08-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_remove_address_email_remove_address_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecontent',
            name='service_title',
            field=models.CharField(default='deneme', max_length=100, verbose_name='Service Title'),
            preserve_default=False,
        ),
    ]
