# Generated by Django 6.0.1 on 2026-01-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='company/'),
        ),
    ]
