# Generated by Django 6.0.1 on 2026-01-14 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_ro', models.CharField(max_length=200, null=True)),
                ('name_tr', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('service_type', models.CharField(choices=[('sourcing', 'Sourcing Solutions'), ('consultancy', 'Consultancy Services')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ro', models.TextField(blank=True, null=True)),
                ('description_tr', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ro', models.CharField(max_length=200, null=True)),
                ('title_tr', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField()),
                ('short_description_en', models.TextField(null=True)),
                ('short_description_ro', models.TextField(null=True)),
                ('short_description_tr', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ro', models.TextField(null=True)),
                ('description_tr', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='services/')),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=100)),
                ('price_info', models.CharField(blank=True, max_length=200)),
                ('price_info_en', models.CharField(blank=True, max_length=200, null=True)),
                ('price_info_ro', models.CharField(blank=True, max_length=200, null=True)),
                ('price_info_tr', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ro', models.CharField(max_length=200, null=True)),
                ('title_tr', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ro', models.TextField(null=True)),
                ('description_tr', models.TextField(null=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Feature',
                'verbose_name_plural': 'Service Features',
                'ordering': ['order'],
            },
        ),
    ]
