# Generated by Django 6.0.1 on 2026-01-14 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Sourcing Solutions, Consultancy Services', max_length=100)),
                ('name_en', models.CharField(help_text='e.g., Sourcing Solutions, Consultancy Services', max_length=100, null=True)),
                ('name_ro', models.CharField(help_text='e.g., Sourcing Solutions, Consultancy Services', max_length=100, null=True)),
                ('name_tr', models.CharField(help_text='e.g., Sourcing Solutions, Consultancy Services', max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ro', models.TextField(blank=True, null=True)),
                ('description_tr', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Types',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='services.servicetype'),
        ),
    ]
