# Generated by Django 6.0.1 on 2026-01-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicetype_alter_servicecategory_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Category image', upload_to='services/categories/'),
        ),
    ]
