# Generated by Django 6.0.1 on 2026-01-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_servicecategory_icon_servicecategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_ro',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_tr',
        ),
    ]
