# Generated by Django 6.0.1 on 2026-01-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(help_text='e.g., Together We Can', max_length=200)),
                ('main_title_en', models.CharField(help_text='e.g., Together We Can', max_length=200, null=True)),
                ('main_title_ro', models.CharField(help_text='e.g., Together We Can', max_length=200, null=True)),
                ('main_title_tr', models.CharField(help_text='e.g., Together We Can', max_length=200, null=True)),
                ('highlight_text', models.CharField(help_text='e.g., Do Anything', max_length=200)),
                ('highlight_text_en', models.CharField(help_text='e.g., Do Anything', max_length=200, null=True)),
                ('highlight_text_ro', models.CharField(help_text='e.g., Do Anything', max_length=200, null=True)),
                ('highlight_text_tr', models.CharField(help_text='e.g., Do Anything', max_length=200, null=True)),
                ('subtitle', models.CharField(help_text='e.g., Better', max_length=300)),
                ('subtitle_en', models.CharField(help_text='e.g., Better', max_length=300, null=True)),
                ('subtitle_ro', models.CharField(help_text='e.g., Better', max_length=300, null=True)),
                ('subtitle_tr', models.CharField(help_text='e.g., Better', max_length=300, null=True)),
                ('tagline', models.TextField(help_text='e.g., Around the World, We Deliver Goods')),
                ('tagline_en', models.TextField(help_text='e.g., Around the World, We Deliver Goods', null=True)),
                ('tagline_ro', models.TextField(help_text='e.g., Around the World, We Deliver Goods', null=True)),
                ('tagline_tr', models.TextField(help_text='e.g., Around the World, We Deliver Goods', null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ro', models.TextField(null=True)),
                ('description_tr', models.TextField(null=True)),
                ('background_image', models.ImageField(upload_to='hero/')),
                ('cta_text', models.CharField(default='Discover now', max_length=100)),
                ('cta_text_en', models.CharField(default='Discover now', max_length=100, null=True)),
                ('cta_text_ro', models.CharField(default='Discover now', max_length=100, null=True)),
                ('cta_text_tr', models.CharField(default='Discover now', max_length=100, null=True)),
                ('cta_link', models.CharField(default='/about/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_position', models.CharField(max_length=200)),
                ('client_image', models.ImageField(upload_to='testimonials/')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=100)),
                ('title', models.CharField(help_text='e.g., Industry Expertise', max_length=200)),
                ('title_en', models.CharField(help_text='e.g., Industry Expertise', max_length=200, null=True)),
                ('title_ro', models.CharField(help_text='e.g., Industry Expertise', max_length=200, null=True)),
                ('title_tr', models.CharField(help_text='e.g., Industry Expertise', max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ro', models.TextField(null=True)),
                ('description_tr', models.TextField(null=True)),
                ('link_text', models.CharField(default='Learn more', max_length=100)),
                ('link_text_en', models.CharField(default='Learn more', max_length=100, null=True)),
                ('link_text_ro', models.CharField(default='Learn more', max_length=100, null=True)),
                ('link_text_tr', models.CharField(default='Learn more', max_length=100, null=True)),
                ('link_url', models.CharField(default='/about/', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Item',
                'verbose_name_plural': 'Why Choose Us Items',
                'ordering': ['order'],
            },
        ),
    ]
