# Generated by Django 6.0.1 on 2026-01-14 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['order'], 'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Sections'},
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='cta_link',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='cta_text_en',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='cta_text_ro',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='cta_text_tr',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='highlight_text',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='highlight_text_en',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='highlight_text_ro',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='highlight_text_tr',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='main_title',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='main_title_en',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='main_title_ro',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='main_title_tr',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='subtitle_ro',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='subtitle_tr',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='tagline_en',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='tagline_ro',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='tagline_tr',
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_link',
            field=models.CharField(default='/about/', max_length=200),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_link_2',
            field=models.CharField(blank=True, help_text='Second button link', max_length=200),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_text',
            field=models.CharField(default='Learn More', max_length=100),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_text_2',
            field=models.CharField(blank=True, help_text='Second button (optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_text_2_en',
            field=models.CharField(blank=True, help_text='Second button (optional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_text_2_ro',
            field=models.CharField(blank=True, help_text='Second button (optional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_text_2_tr',
            field=models.CharField(blank=True, help_text='Second button (optional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_text_en',
            field=models.CharField(default='Learn More', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_text_ro',
            field=models.CharField(default='Learn More', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_text_tr',
            field=models.CharField(default='Learn More', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herosection',
            name='image',
            field=models.ImageField(blank=True, help_text='Hero section image', upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='main_heading',
            field=models.CharField(default=django.utils.timezone.now, help_text='e.g., Leading Sourcing And Consultancy Firm', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herosection',
            name='main_heading_en',
            field=models.CharField(help_text='e.g., Leading Sourcing And Consultancy Firm', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='main_heading_ro',
            field=models.CharField(help_text='e.g., Leading Sourcing And Consultancy Firm', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='main_heading_tr',
            field=models.CharField(help_text='e.g., Leading Sourcing And Consultancy Firm', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='herosection',
            name='welcome_text',
            field=models.CharField(default='', help_text='e.g., Welcome To Avanti Global', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herosection',
            name='welcome_text_en',
            field=models.CharField(help_text='e.g., Welcome To Avanti Global', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='welcome_text_ro',
            field=models.CharField(help_text='e.g., Welcome To Avanti Global', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='welcome_text_tr',
            field=models.CharField(help_text='e.g., Welcome To Avanti Global', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=models.TextField(help_text='Main description text'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='description_en',
            field=models.TextField(help_text='Main description text', null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='description_ro',
            field=models.TextField(help_text='Main description text', null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='description_tr',
            field=models.TextField(help_text='Main description text', null=True),
        ),
    ]
