# Generated by Django 6.0.1 on 2026-01-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_herosection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='description_ro',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='description_tr',
        ),
    ]
