# Generated by Django 6.0.1 on 2026-01-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_herosection_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whychooseus',
            name='icon',
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='image',
            field=models.ImageField(default='', help_text='Why choose us image', upload_to='why-choose-us/'),
            preserve_default=False,
        ),
    ]
