# Generated by Django 6.0.1 on 2026-01-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='AVANTI GLOBAL SRL', max_length=200)),
                ('tagline', models.CharField(help_text='Leading Sourcing And Consultancy Firm...', max_length=300)),
                ('tagline_en', models.CharField(help_text='Leading Sourcing And Consultancy Firm...', max_length=300, null=True)),
                ('tagline_ro', models.CharField(help_text='Leading Sourcing And Consultancy Firm...', max_length=300, null=True)),
                ('tagline_tr', models.CharField(help_text='Leading Sourcing And Consultancy Firm...', max_length=300, null=True)),
                ('main_description', models.TextField(help_text='Company introduction')),
                ('main_description_en', models.TextField(help_text='Company introduction', null=True)),
                ('main_description_ro', models.TextField(help_text='Company introduction', null=True)),
                ('main_description_tr', models.TextField(help_text='Company introduction', null=True)),
                ('mission', models.TextField()),
                ('mission_en', models.TextField(null=True)),
                ('mission_ro', models.TextField(null=True)),
                ('mission_tr', models.TextField(null=True)),
                ('vision', models.TextField()),
                ('vision_en', models.TextField(null=True)),
                ('vision_ro', models.TextField(null=True)),
                ('vision_tr', models.TextField(null=True)),
                ('approach_title', models.CharField(default='Our Approach', max_length=200)),
                ('approach_title_en', models.CharField(default='Our Approach', max_length=200, null=True)),
                ('approach_title_ro', models.CharField(default='Our Approach', max_length=200, null=True)),
                ('approach_title_tr', models.CharField(default='Our Approach', max_length=200, null=True)),
                ('approach_description', models.TextField()),
                ('approach_description_en', models.TextField(null=True)),
                ('approach_description_ro', models.TextField(null=True)),
                ('approach_description_tr', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='about/')),
                ('video_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
            },
        ),
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ro', models.CharField(max_length=200, null=True)),
                ('title_tr', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ro', models.TextField(null=True)),
                ('description_tr', models.TextField(null=True)),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company Value',
                'verbose_name_plural': 'Company Values',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('position_en', models.CharField(max_length=200, null=True)),
                ('position_ro', models.CharField(max_length=200, null=True)),
                ('position_tr', models.CharField(max_length=200, null=True)),
                ('bio', models.TextField()),
                ('bio_en', models.TextField(null=True)),
                ('bio_ro', models.TextField(null=True)),
                ('bio_tr', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='team/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
    ]
