# Generated by Django 6.0.1 on 2026-01-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description_ro',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description_tr',
        ),
    ]
